/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codelevelsecurity;

import codelevelsecurity.beans.UserBean;
import codelevelsecurity.services.UserActivityServices;
import java.awt.Container;
import java.awt.Toolkit;
import javax.xml.soap.Detail;
/**
 *
 * @author Taranpreet Kaur
 */
public class MainFrame extends javax.swing.JFrame {

    private int id;
    public static Container c;
    private UserBean objbean;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(int id, UserBean objbean) {//to pass(int Userid) as argument

        setUndecorated(true);
        initComponents();

        this.id = id;
        this.objbean= objbean;
        setSize(Toolkit.getDefaultToolkit().getScreenSize());//to set the size of screen
        setResizable(false);
        c = this.getContentPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        mnuUsermaintenance = new javax.swing.JMenu();
        miUserAccountdetail = new javax.swing.JMenuItem();
        mnuJavaIde = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserAccountReport = new javax.swing.JMenuItem();
        miProgramReport = new javax.swing.JMenuItem();
        miSavedProgram = new javax.swing.JMenuItem();
        miUpdatedProgram = new javax.swing.JMenuItem();
        miAccessedProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        mnuProfile.setText("Profile");
        mnuProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfileActionPerformed(evt);
            }
        });

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        jMenuBar1.add(mnuProfile);

        mnuUsermaintenance.setText("User Maintenance");
        mnuUsermaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsermaintenanceActionPerformed(evt);
            }
        });

        miUserAccountdetail.setText("User Account Detail");
        miUserAccountdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountdetailActionPerformed(evt);
            }
        });
        mnuUsermaintenance.add(miUserAccountdetail);

        jMenuBar1.add(mnuUsermaintenance);

        mnuJavaIde.setText("Java Ide");

        miOpen.setText("Open");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        mnuJavaIde.add(miOpen);

        jMenuBar1.add(mnuJavaIde);

        mnuReports.setText("Reports");

        miUserAccountReport.setText("User Account Report");
        mnuReports.add(miUserAccountReport);

        miProgramReport.setText("Program Report");
        mnuReports.add(miProgramReport);

        miSavedProgram.setText("Saved Program ");
        mnuReports.add(miSavedProgram);

        miUpdatedProgram.setText("Updated Program");
        mnuReports.add(miUpdatedProgram);

        miAccessedProgram.setText("Accessed program");
        mnuReports.add(miAccessedProgram);

        jMenuBar1.add(mnuReports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUserAccountdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountdetailActionPerformed
        c.removeAll();
        c.setVisible(false);
        ManageUsers objmu = new ManageUsers();
        objmu.setBounds(200, 10, 500, 700);
        c.add(objmu);
        c.setVisible(true);
    }//GEN-LAST:event_miUserAccountdetailActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        new UserActivityServices().UpdateLogoutTime(id);
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_miLogoutActionPerformed

    private void mnuUsermaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsermaintenanceActionPerformed
        UserReport udr = new UserReport();
        udr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuUsermaintenanceActionPerformed

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        c.removeAll();
        c.setVisible(false);
        ProfileDetail pd = new ProfileDetail(objbean.getUserid());//to get the id from login frame
        pd.setBounds(200, 10, 500, 700);
        c.add(pd);
        c.setVisible(true);
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void mnuProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProfileActionPerformed

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
        // TODO add your handling code here:
        IDE obj = new IDE();
        obj.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_miOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAccessedProgram;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miProgramReport;
    private javax.swing.JMenuItem miSavedProgram;
    private javax.swing.JMenuItem miUpdatedProgram;
    private javax.swing.JMenuItem miUserAccountReport;
    private javax.swing.JMenuItem miUserAccountdetail;
    private javax.swing.JMenu mnuJavaIde;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuUsermaintenance;
    // End of variables declaration//GEN-END:variables
}
